### ISSUE TITLE
ECR folder structure for Dev, QA, Stage and Prod environments

### ISSUE THREAD

**Issue by RaoBhethanabotla** [saayam-for-all/devsecops#4]
We have four environments - dev, qa, stage and prod. All the deliverables for all the environments will be moved to ECR in respective folders. Here is an example folder structure:

ECR/saayam/dev/volunteer/...
                     /qa/volunteer/....
                     /stage/volunteer/...
                     /prod/volunteer/...

**Comment by Sakshi895** [comment]
Created folder structure for all the microservices for their respective qa, stage, prod and dev branch.
